version: '2'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: test
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - "33061:3306"
  redis:
    build: ./redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./redis/data:/data
  web:
    image: nginx
    restart: always
    ports:
      - "${PHP_PORT}:80"
    volumes:
      - ${SRC_ROOT}:/app
      - ./nginx/sites/${ENV}.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/${ENV}.default.conf:/etc/nginx/${ENV}.default.conf
    links:
      - php

  php:
    extends:
      file: base-php/base-php.yml
      service: base-php
    restart: always
    working_dir: /app
    user: '1000:1000'
    volumes:
      - ${SRC_ROOT}:/app
    links:
      - db
      - redis
